package intent

import "tmux-fsm/weaver/core"

// Adapter adapts a standard `intent.Intent` to the `core.Intent` interface,
// allowing the new weaver system to process intents generated by older parts
// of the system.
type Adapter struct {
	Intent
}

func (a *Adapter) GetKind() core.IntentKind {
	return core.IntentKind(a.Kind)
}

func (a *Adapter) GetTarget() core.SemanticTarget {
	return core.SemanticTarget{
		Kind:      int(a.Target.Kind),
		Direction: a.Target.Direction,
		Scope:     a.Target.Scope,
		Value:     a.Target.Value,
	}
}

func (a *Adapter) GetCount() int {
	return a.Count
}

func (a *Adapter) GetMeta() map[string]interface{} {
	return a.Meta
}

func (a *Adapter) GetPaneID() string {
	return a.PaneID
}

func (a *Adapter) GetSnapshotHash() string {
	return a.SnapshotHash
}

func (a *Adapter) IsPartialAllowed() bool {
	return a.AllowPartial
}

func (a *Adapter) GetAnchors() []core.Anchor {
	coreAnchors := make([]core.Anchor, len(a.Anchors))
	for i, anchor := range a.Anchors {
		coreAnchors[i] = core.Anchor{
			PaneID: anchor.PaneID,
			Kind:   core.AnchorKind(anchor.Kind),
			Ref:    anchor.Ref,
			Hash:   anchor.Hash,
			LineID: core.LineID(anchor.LineID),
			Start:  anchor.Start,
			End:    anchor.End,
		}
	}
	return coreAnchors
}
